# Sponsor Open Communication / Vākya Protocol
# These are supported funding model platforms

github: prakashgarg91
ko_fi: prakashgarg91
buy_me_a_coffee: prakashgarg91
custom: ["https://opencollective.com/open-communication", "https://paypal.me/prakashgarg91"]
